#2 issue-2 add resolve class for interface
nikolaposa/cascader pull request #3
Opened 2018-08-29 09:26 UTC by alexpts

PR for #2 and https://github.com/nikolaposa/monolog-factory/issues/3

2018-09-01 16:08 UTC, nikolaposa requested changes
I like the idea with special `__class__` key in options, but I think that making this library aware of `options` as an another special key feels awkward and is not necessary. I would rather keep things as simple as possible, just by introducing that one special argument, so that the class can be constructed this way:

```
$cascader->create(BufferHandler::class, [
    'handler' => [
        '__class__' => NativeMailHandler::class, //this one gets removed from options after you pick it up
        'to' => 'test@example.com',
        'subject' => 'Test',
        'from' => 'noreply@example.com',
        'level' => Logger::ALERT,
    ],
    'buffer_limit' => 5
]);
```

2018-09-01 20:26 UTC, alexpts commented
@nikolaposa, I will send commit for it.

2018-09-02 05:43 UTC, alexpts commented
I fixed the comments about flat format

2018-09-02 08:10 UTC, nikolaposa approved these changes

2018-09-02 08:11 UTC, merged